# Generated by Django 6.0.3 on 2026-04-19 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Field name or plot identifier', max_length=200)),
                ('crop_type', models.CharField(help_text='Type of crop, e.g. Maize, Tomatoes', max_length=100)),
                ('planting_date', models.DateField(help_text='Date the crop was planted')),
                ('location', models.CharField(blank=True, help_text='Optional: county/ward/coordinates', max_length=200)),
                ('current_stage', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('ready', 'Ready to Harvest'), ('harvested', 'Harvested')], default='planted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_harvest_date', models.DateField(blank=True, help_text='When is this field expected to be ready for harvest?', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin-level notes about this field')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='The field agent responsible for this field', limit_choices_to={'role': 'field_agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fields', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_at_update', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('ready', 'Ready to Harvest'), ('harvested', 'Harvested')], max_length=20)),
                ('notes', models.TextField(help_text='Observations, issues, measurements, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='fields.field')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
